### ISSUE TITLE
Проблемы нового UI

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#303]
- [x] 1. Не отображается счетчик просмотров под постами 

- [x] 2. Сломались превьюшки 

- [x]  3.При нажатии на кнопку "Показать больше постов..." (вкладка "новое", под тегами, видны посты бм)

- [x]  4. Нотификации (уведомления)

- [x] 5. Шаринг ФБ

- [x] 6. Первые 4 пункта меню в боковом меню, захардкодены и не переводится на другие языки

- [x] 7. В настройках, при блокировки юзеров, Появляется окно Muted Users (перевести на "Заблокированные пользователи" 

- [x] 8. Наличие старой сессии, выдает ошибку, при которой необходимо чистить куки / историю  

- [x] 9. Вернуть Шрифты (сериф в посте и санс в комментах и остальных местах)(c засечками)

- [x] 10. Следующее понижение Силы Голоса запланировано на  через 7 дней. Перевести как:
Следующее понижение силы голоса произойдет через 7 дней

- [x] 11. Заменить подписаться на главной заставке на "зарегистрировавшись" 

- [x] 12. Сделать отображение ссылок полными активными линками ([см.](https://github.com/GolosChain/tolstoy/issues/303#issuecomment-283452667))

- [x] 13. Сделать актуальный пробел между превью картинки и превью текста ([см.](https://github.com/GolosChain/tolstoy/issues/303#issuecomment-283594194))

- [x] 14. У ряда пользователей слетел период регистрации (юзеры снепшота стима 29.09.2016 12:00)

- [x] 15. https://golos.io/tags/trending - отсутствует какая либо информация
pavit: Надо разбираться. Вот такой ответ приходит по запросу от демона:
```
"10 assert_exception: Assert Exception !ec: websocket send failed: A payload contained invalid data
    {"msg":"A payload contained invalid data"} th_a  websocket.cpp:164 send_message
    {"call.method":"call","call.params":[0,"get_state",["/tags/hot"]]} th_a  websocket_api.cpp:124 on_message"
```

- [x] 16. Не правильно отображается репутация на фронте

- [x] 17. Фильтр тегов не работает корректно

- [ ] 18. В теле текста Русские [теги не читаются](https://golos.io/error/@vik/fucked#@vik/re-sheriff-re-vik-fucked-20170308t080233261z)

- [x] 19.1 На странице /about в подвале не переходит по ссылке страница https://golos.io/legal/terms_of_service.pdf

- [x] 19.2 Нет ссылки на https://golos.io/ru--golos/@golos/golos-russkoyazychnaya-socialno-mediinaya-blokchein-platforma
Должна быть сверху со всеми кнопками под названием White Paper 

- [x] 20. Исправить [грамматическую ошибку](https://golos.io/ru--obratnaya-svyazx/@crombrugger/grammaticheskaya-oshibka-vo-fraze-privetstviya) приветствия.

- [x] 21. Не работают [Другие теги](https://golos.io/tags/trending). 

- [x] 22. Пользовательская страница не отображается ([пример](https://golos.io/@vik))

- [x] 24. В постах и комментариях не парсится юзернейм вида @user если после упоминания идет пустая строка (без видимых символов) [примеры](https://github.com/GolosChain/tolstoy/issues/303#issuecomment-284263492)

**Comment by litrbooh** [comment]
у меня значек рублей не отображается

**Comment by serejandmyself** [comment]
@litrbooh кеш и куки попробуй и перезапуститсь

**Comment by litrbooh** [comment]
ну я всё почистил и только зашел

**Comment by serejandmyself** [comment]
Какой брузер?

**Comment by litrbooh** [comment]
лиса

**Comment by solodikov** [comment]
По шрифтам хочу сразу прокомментировать.
Сейчас шрифт - с засечками - это считается крайне не оптимальным. Раньше был "пляшущий" шрифт - тоже не айс.

Как минимум - пока нужно сделать как у Стимита **сейчас**: цвет, кегль.
Наш "сейчас" не как у Стимита "сейчас".

В идеале нужен чёткий прямой шрифт.
Будем ставить прямой?

**Comment by serejandmyself** [comment]
Уже несколько людей попросили как было. Давайте сделаем как было

**Comment by solodikov** [comment]
Тогда лучше хотя бы как у Стимита сейчас. Это почти как было, только лучше.

**Comment by serejandmyself** [comment]
Но все просят как было (а они все сидят на стимите). Давайте сделаем как просят

**Comment by litrbooh** [comment]
Как на стимите мне не нравится, на голосе было лучше.

**Comment by litrbooh** [comment]
![default](https://cloud.githubusercontent.com/assets/22373216/23469862/eff904c0-feb5-11e6-9c70-1748721283da.png)
Криво отображается Новое. (было ещё на предыдущей версии)
Приходится скролить вверх, вниз - тогда подгружается.

**Comment by AlekseiSmirnov** [comment]
> Следующее понижение Силы Голоса запланировано на  через 7 дней.

Я бы перевёл так: "Следующее понижение силы голоса произойдет через 7 дней"

**Comment by valzav** [comment]
> Сейчас шрифт - с засечками - это считается крайне не оптимальным. Раньше был "пляшущий" шрифт - тоже не айс.

Сериф считается оптимальным для длинных текстов. Санс в коментах нормально.

**Comment by solodikov** [comment]
> Сериф считается оптимальным для длинных текстов. Санс в коментах нормально.
Я этим занимался, это "не совсем так".
У нас на рядовой странице - не менее 10 шрифтовых вариаций.
Это категорически не корректно.

**Comment by valzav** [comment]
Так оставьте две вариации - сериф в посте и санс в коментах и остальных местах

**Comment by solodikov** [comment]
Плюс, нужно отстроить кегли, болды и цвета.

**Comment by solodikov** [comment]
![screenshot 2017-03-02 0 56 14](https://cloud.githubusercontent.com/assets/24874226/23478575/94e762d8-fee3-11e6-8e18-b31c34dabd15.jpg)
Ссылки не отображаются полными линками, только половиной.

**Comment by litrbooh** [comment]
слово подписаться тут не в тему, наверно "зарегистрировавшись"
![default](https://cloud.githubusercontent.com/assets/22373216/23480483/263af2dc-fed9-11e6-9279-0c1abd84128f.png)

**Comment by litrbooh** [comment]
Добавьте плиз в FAQ - https://golos.io/about#faq

Мой FAQ, если ничего лучше нет: https://golos.io/ru--golos/@litrbooh/sozdaem-novyi-faq-dlya-socialnoi-seti-golos

**Comment by serejandmyself** [comment]
Уже есть /welcome, оно доступно либо с бокового меню, либо после регистрации, либо пока нет подписок ни на кого, ссылка на эти доки отображается в пустой ленте

**Comment by litrbooh** [comment]
а в FAQ что будет?

**Comment by litrbooh** [comment]
Криво отображаются списки?

В редакторе:
![default](https://cloud.githubusercontent.com/assets/22373216/23483398/d396a192-fee3-11e6-8026-c64c4aa76925.png)

В посте:
![default](https://cloud.githubusercontent.com/assets/22373216/23483416/e7b5a88a-fee3-11e6-9b52-c253dee15c79.png)

**Comment by feruzm** [comment]
<img width="357" alt="screen shot 2017-03-02 at 7 26 49 am" src="https://cloud.githubusercontent.com/assets/3015990/23494179/cdd91754-ff19-11e6-974f-97776317dee0.png">

**Comment by litrbooh** [comment]
Да, можно для тех у кого даты входа нет, поставить хотя бы дату переноса акков в Голос

**Comment by 0n0t0le** [comment]
Баг в кошельке

![](https://s8.postimg.org/gqok13yth/image.png)

Естественно PD не запускал...

**Comment by solodikov** [comment]
@pavelit, вот здесь, смотри, красной линией я пометил линию склейки превью текста с превью картинки. Там должен быть актуальный пробел.

![screenshot 2017-03-02 13 48 14](https://cloud.githubusercontent.com/assets/24874226/23499878/b605a314-ff4f-11e6-9df6-6ec85e11f6c9.jpg)

**Comment by mguryeva** [comment]
https://golos.io/ru--khardfork/@anyone/syurprizy-khardforka
пользователи Голоса уже обратили внимание на

амнистию по репутации,
удаление старых юзерпиков и
появление обтекания картинок в постах текстом справа по умолчанию.

Что-то не то с украинской версией

**Comment by mguryeva** [comment]
https://golos.io/ru--golos/@vasyl73/bag-ukrayinskii-interfeis-golosu-ta-plyus-golosu-tegi-ukrayinskoyu
Український інтерфейс уже недоступний :-(

Надіюсь, що це буде виправлено. В принципі це не критично і юзаю англомовний.

Зате величезний респект за українські теги.

Тепер можна замінити тег " ua " на "україна" . Дякую :-)

Правка після публікації

:(((

**Comment by mguryeva** [comment]
https://golos.io/ru--obratnaya-svyazx/@ondulyansion/problemy-s-otobrazheniem-postov

**Comment by mguryeva** [comment]
https://golos.io/ru--golos/@boddhisattva/bag-khardforka
Обнаружил сегодня у себя в кошельке вот такое.




Я понижение Силы Голоса никогда не запускал. Допустим я хочу ее запустить, но соответствующей кнопки нет.

Это у всех так? Если не сложно, те, кто прочитал это сообщение, сообщите, так ли у вас?

PS: Я, конечно, подозреваю, что вряд ли ХФ запустил powerdown без моего ведома. В таком случае мое сообщение - это уведомление о баге.

**Comment by solodikov** [comment]
@mguryeva, у меня - корректно.

**Comment by mguryeva** [comment]
@solodikov , проблема не у меня. Свяжитесь, пж, с автором поста

**Comment by solodikov** [comment]
@mguryeva, я по выявлению сразу прокомментировал пользователя.

**Comment by valzav** [comment]
По моему с серифом было лучше, сравните:

![](https://www.evernote.com/shard/s9/sh/a38414cf-af4e-47bc-bf4f-48d720231a9c/ed1e3c4b8ed7a916/res/210b5b95-5757-47a5-aa3d-a1a9af715eeb/skitch.png?resizeSmall&width=832)

**Comment by serejandmyself** [comment]
Да, шрифты не те

**Comment by solodikov** [comment]
13 пункт стоит в исполненных?
Ничего не поменялось. Куки-кеша чистые.

**Comment by t3ran13** [comment]
ребята, верните старые шрифты! все же было круто! а сейчас просто жесть полная

**Comment by t3ran13** [comment]
http://screencloud.net/v/uW9hA

**Comment by t3ran13** [comment]
мб сделайте в настройки пару "тем", чб можно было выбрать???

**Comment by t3ran13** [comment]
http://screencloud.net/v/ENBLr 
мне нравится на 40% меньше

**Comment by t3ran13** [comment]
про заголовки я вообще молчу

**Comment by t3ran13** [comment]
кстати, давайте такое заливать на стейджинг и опрос устаивать??? или делать скриншоты и пускай по скриншотам люди выберут
а то на рабочем проекте такое делать не дело совсем

**Comment by litrbooh** [comment]
@serejandmyself,  я не понят твою ссылку с отсутствием уведомлений сюда.  В первом посте не вижу включения этой проблемы  в работу.

И второй вопрос. Как смотреть посты БМ?
https://golos.io/trending/bm-open

**Comment by serejandmyself** [comment]
@t3ran13 Настройка шрифтов не закончена. Если видишь то галочки не стоят, а это значит что мы не закончили работы над этой темой.

@litrbooh странно что ты спрашиваешь, ведь я вчера написал в чате делегатов подробно в чем проблема. Опять же, как видишь не стоит галочка на против слов "нотификации" - это значит, что работа не окончена.

**Comment by serejandmyself** [comment]
Посты bm доступны только по прямым ссылкам

**Comment by litrbooh** [comment]
@serejandmyself , извини, я просто уже писал, что не понимаю русский текст, в котором используются отсутствующие в русском языке слова, поэтому я прочитал, но не понял что речь об уведомлениях. :)

**Comment by serejandmyself** [comment]
исправил специально для тебя =)

**Comment by t3ran13** [comment]
@serejandmyself  спс, только если можно на проде не тренироватсья

**Comment by serejandmyself** [comment]
@t3ran13 О чем речь? Наши тестовые сети были доступны всем желающим делегатам на протяжении 2 недель до релиза. О шрифтах не было речи, соответственно шрифт был выпущен, тот который был на тестнете.

**Comment by t3ran13** [comment]
@serejandmyself на старте шрифт был норма, сегодня он стал огромным

**Comment by t3ran13** [comment]
кстати, а где наши уведомления и счетчик просмотров???

**Comment by serejandmyself** [comment]
@t3ran13 это другой шрифт, не тот который на старте, проблема известна, исправим. 

Насчет счетчика и уведомлений. см. выше

**Comment by t3ran13** [comment]
@serejandmyself 
спс
по поводу шрифта, он в таблицах почему-то малость больше, можно его сделать таким же как в тексте по пикселям?

**Comment by primusd** [comment]
Надо категорически срочно править отображение постов в "Новом".

Источник проблемы уже найден (посты БМ), надо срочно исправить.

Сейчас практически невозможно читать ленту новых постов, что вызывает разочарование у всех пользователей, а новым авторам не даёт ни малейшего шанса быть замеченными.

**Comment by t3ran13** [comment]
Что поменялось с меню тегов на главной, там тега пифотопремия нет совсем. я напрямую выгребаю из ноды блоечейна методом GetTrendingCategories и там он присутствует. Раньше все соответсвовало один в один, а сейчас вообще не понятно что там такое.

**Comment by serejandmyself** [comment]
@primusd мы в курсе проблемы, так как сами её описали еще вчера.Для этого был подготовлен RC 16.4

**Comment by serejandmyself** [comment]
@t3ran13 Меню тегов не формируется по принципу популярные теги... Оно формируется по принципу ценности комментариев к этому тегу

**Comment by t3ran13** [comment]
@serejandmyself где почитать подробнее об этом чб понять работу? и каким запросом мне получить список этих тегов из блокчейна? и кстати как получить перевод тегов?

**Comment by 0n0t0le** [comment]
В постах и комментариях не парсится юзернейм вида @user если после упоминания идет пустая строка (без видимых символов)
Пример ниже:
![](https://s21.postimg.org/pxsehiaev/image.png)

**Comment by mguryeva** [comment]
https://golos.io/created/%D0%94%D0%B5%D1%81%D1%8F%D1%82%D1%8C%D1%84%D0%B0%D0%BA%D1%82%D0%BE%D0%B2%D0%BE%D0%B1%D0%BE%D0%BC

**Comment by mguryeva** [comment]
Поиск по тэгам на главной странице не работает... Проверяю на идунавзлет (тэг точно существует, но не отображается и не ищется)
![image](https://cloud.githubusercontent.com/assets/7629337/24115003/11f32b8a-0db3-11e7-88f5-257fb174f1dd.png)

**Comment by serejandmyself** [comment]
@mguryeva Логика поиска не работает по тегам, только по категориям. Также, она не работает по Русским категориям (не включена транслитация). На данный момент мы не нашли решения проблемы (для поиска по тегам и по категориям), поэтому, во избежания путаницы людей (разница между тегом и категорией), пока что фильтр будет отключен
