### ISSUE TITLE
Тестнет 17 недочеты

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#363]
- [x] 1. Текст при регистрации

- [x] 2. Текст Фильтра тегов

- [x] 3. Текст при отсутствии постов во вкладках

- [x] 4. Кнопка Обратная связь

- [x] 5. текст в Ленте при отсутствии подписок на авторов

- [x] 6. Окошко выбора выплаты (размер и текст) - при "написать пост"

- [x] 7. Текст на странице "блог" под ником

- [x] 8. Кнопки (купить / продать - НЕ рынок) в кошельке в нескольких местах

- [x] 9. Почти все опции в кошельке (при нажатии на стрелки) - переводы / недочеты

- [x] 10. Небезопасный для работы (NSFW) контент - это старый перевод, взять из голоса

- [x] 11. Показать больше меньше сообщений низкой стоимости - старый текст, взять из голоса

- [x] 12. Вкладка "разрешения" - там вообще жесть 

- [x] 13. Текст во вкладке пароль 

- [x] 14. Кнопка редактор пропадает при написании поста 

- [x] 15. Слово "Title" в новом посте

- [x] 16. Вкладка "Продвигаемое", нужно "Промо"

- [x] 17. Нет возможности написать пост 

- [x] 18. Нет вкладки Domestic

- [x] 19. Текст для добавления картинок в пост (не читабельно)

- [x] 20. Кнопку О проекте перенести влево, на верхней части хедера. Справа от логотипа и сделать её фон не зеленым, а более подходящим цветовой гамме

- [x] 21. Кнопку обратная связь, тоже сделать не на зеленом фоне, а на более мягком, с соотвестующей цветовой гаммой

- [x] 22. Поле теги (справа), должно занимать меньше места от всего экрана (смотрите Steem, но у нас есть фильтр тегов. В общем решение должно быть посередине)

- [x] 23. Во вкладке /market много ошибок. Например значки Рубля в заказах на продажу и на покупку. Поле "купить" и "продать" - цена: должно быть не GBG/ГОЛОС, а просто GBG

- [x] 24. В дроп даун меню, справа (три полоски): Кнопка обратная связь написано большими буквами, это лишнее. Слово wiki не переведено. Белая книга Голос... В общем, надо взять версию которая сейчас на Голосе этого меню   

- [x] 25. Проверить все мета теги, тайтлы, дескрипшн, ГА, Яндекс метрику 

- [x] 26. Иконки вылезают на лого в мобильной версии 

- [x] 27. Отсутствие указания силы голоса

- [x] 28. Перенести иконку чата вверх (оставить цветной)

- [x] 29. Нерабочие ссылки в правом верхнем углу на странице about

- [x] 30. Перевод интерфейса на другие языки, отсутствует 

- [x] 31. Соц сети для шаринга из стима, а не не те что должны быть

- [x] 32. Картинки из буфера не вставляются в пост

- [x] 33. Отсутствует ГУИ для продления выплат

- [x] 34. Добавить в заголовке страницы иконку карандаш - написать пост

- [x] 35. Вынести переменные валют и другие в языковые файлы (#341, #342)

- [x] 36. В разделе "Добавить пост" перенести "выбор языка контента" слева от ссылки "редактор". Оформить в виде ссылки с всплывающем меню.

- [x] 37. Добавить оценку стоимости аккаунта на главную (под добавить пост) - возможно просто писать значок валюты (например рубли) и сумму

- [x] 38. При отправлении токенов голос (передать в кошельке, написано "Эта заметка является приватной" . Заменить слово "приватной" на "публичной"

- [x] 39. "Отправить на счет" Заменить на "Отправить в сейф"  (токены голос)

- [x] 40. При нажатии на уменьшить силу голоса, выскакивает фраза:
Эта операция требует ввода Вашего ключа владельца или ввода Вашего активного ключа (используйте главный пароль)
Заменить её на:
Эта операция требует ввода Вашего ключа владельца или ввода Вашего активного ключа 

- [x] 41. При отправлении токенов Золотой (передать в кошельке, написано "Эта заметка является приватной" . Заменить слово "приватной" на "публичной"

- [x] 42. "Отправить на счет" Заменить на "Отправить в сейф"  (токены Золотой)

- [x] 43. Слово биржа (токены золотой), заменить на "Купить или продать"

- [x] 44. В кураторских наградах пропало склонение (СилЫ Голоса) а не  (СилА Голоса) 

- [x] 45. При нажатии на кнопку обратная связь, в теле поста, не отображается заголовок и варианты вознаграждения. Также требуется добавить тусклым цветом, по вверх тела текста (вместо "ответить"), текст из #311 

- [x] 46. Дернуть иконки из стимит для правого меню (которое всплывает при нажатии на аватарку) 

- [x] 47. При выборе языка, должна быть опция (самая первая) - "Показать все"

- [x] 48. В "популярном" вместо "30 дней", должна быть вкладка "За все время"  

- [x] 49. Иконки для шаринга в соц сетях, из стима - у нас - ФБ, ВК, Твитер 

- [x] 50. При создании аккаунта через БЧ, выдается ключ. При вводе этого ключа - не хватает перевода. Вставить текущий перевод из Голоса

- [x] 51. РУССКИЕ ТЕГИ!

- [x] 52. Отказаться от выплат, визуально на клиенте осталась как в Голосе, а должна быть как в Steemit 

- [x] 53. При отсутствии подписок на кого либо и нажатии на фильтр "лента" есть текст, на данный момент он звучит как Не на Русском. Надо заменить его на тот текст который сейчас на Голосе

- [x] 54. При подгрузки картинки из буфера появляется слово UPLOADING. Перевести на Русский - Загружается

- [x] 55. В кошельке, при нажатии на стрелочку возле токенов Голос и Золотой есть опция "перевести НА сейф", нужно заменить на "перевести в сейф" 

- [x] 56. Исчезли все падежи из #50 + корректные склонения глаголов! Не внимательно сделан перевод... Например "Получить 500.000 Сила Голоса от" должно быть как на Голосе "Получено 500.000 Силы Голоса от"

- [x] 57. Добавить Румынский и Сербский язык в национальные

- [x] 58. При смене национального языка, некоторые флаги либо отсутствуют, либо теряют цвет. Также, требуется сменить флаг США на флаг Великобритании при выборе Английского языка

- [x] 59. На фронте видно 2 кнопки "добавить пост" если не залогинен 

- [x] 60. При выборе нац. языка, выбранная опция должна оставаться в списке выбора, но не активная. Например выделенная светло-серым цветом.

- [x] 61. Перенести файлы переводов в crowdin.com. Теперь любой желающий может переводить на свой нац. язык наше приложение. Ссылка для инвайта https://crowdin.com/project/golosio/invite

- [x] 62. Добавить в изоморфный феч корректный вывод валюты

- [x] 63. СМС регистрация

- [x] 64. Флаги стран в текстовом виде 🇯🇵 🇰🇷 🇩🇪 🇨🇳 🇺🇸 🇫🇷 🇪🇸 🇮🇹 🇷🇺 🇬🇧 (http://emojipedia.org/flags/) решили не делать и вернулись к svg 

- [x] 65. Кнопка поделиться в ЖЖ

- [x] 66. После перезагрузки страницы всегда устанавливается "Язык по умолчанию". Необходимо учитывать выбранный пользователем язык.

- [x] 67. Исправить опечатку: СГЕНЕНИРОВАТЬ вместо СГЕНЕРИРОВАТЬ. Ошибка во вкладке @USERNAME/passwords

**Comment by vadbars** [comment]
В форме регистрации генерируется пароль, а ниже надпись ПОВТОРНО ВВЕДИТЕ ПАРОЛЬ
Как обычный юзер, задаю вопрос - надо вводить этот сгенерированный  или свой?
Путает слово ПОВТОРНО (edited)
Юзер же еще никакой не вводил, почему повторно

**Comment by vadbars** [comment]
Текст на странице /welcome надо доработать.

Некоторые заголовки маркдаун некорректно отработал :
**Не теряйте свой пароль! **
Регистрируясь на сайте, вы ознакомились с соглашением хранить свой пароль в безопасности.
Пожалуйста, следуйте этому правилу.
**Сколько я смогу тут заработать? **

Абзац по выплатам после ХФ уже не будет соответствовать реальности:
Выплаты
Существуют 2 окна выплат. Первое от 24 – 48 часов. И второе 30 дней. ....

**Comment by vadbars** [comment]
В тестнете на странице /@username/settings есть поле О ПРОЕКТЕ
На golos.io это поле имеет название ИНФОРМАЦИЯ О ВАШЕМ БЛОГЕ, более понятное имхо. Баг или фича?

**Comment by vadbars** [comment]
На лендинге /about#faq обещается 5 голосов бесплатно. При регистрации сейчас на баланс поступает 3 голоса, не?

**Comment by vadbars** [comment]
При подписке или отписке от пользователя во всплывающем окне сообщение "missing translation: ru.g.confirm_unfollow"

**Comment by vadbars** [comment]
"Похоже, что test1 еще не написал постов!" во вкладке Комментарии. 
Правильнее Похоже, что test1 еще не написал комментариев!" или Похоже, что test1 еще не ничего не комментировал!"

**Comment by vadbars** [comment]
В Кошельке разнобой в именовании токена Голос. В колонке баланса все считается в GOLOS, а в описании то Голос, то GOLOS. 
Например, "Оценочная стоимость рассчитывается из 7-ми дневной средней стоимости Голос".
Но "Перемещаемые цифровые токены, цена которых равна ~1 мг золота в GOLOS."

**Comment by vadbars** [comment]
Кошелек. Пункт со ссылкой на внутреннюю биржу (https://testnet.golos.io/market) в одном меню называется "Купить иди Продать", в в другом "Биржа".
Надо бы унифицировать.

**Comment by vadbars** [comment]
В разделе Разрешение есть ключ Заметка. Непонятно, что это. Может написать так: "Ключ заметок используется для создания и чтения заметок при отправке токенов". 
В Стиме он называется Memo, На биржах тоже. Может быть и не переводить название этого служебного поля.
