### ISSUE TITLE
Разработка редактора статей и комментариев

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#453]
- [x] изучить  и внедрить medium-editor вместо html редактора, сохранять как маркдаун https://yabwe.github.io/medium-editor/demo.html https://yabwe.github.io/medium-editor/

- [ ] изучить Ory.edidor для создания лендингов на голосе https://editor.ory.am/?utm_source=github&utm_medium=header&utm_campaign=editor

**Comment by b1acksun** [comment]
https://app.classeur.io/#!/files/3Nt0HoEqiKTcH0Zxmx3g

**Comment by NickShtefan** [comment]
- [ ] Внедрить Medium Editor
- [ ] Привести к Markdown виду форматирование текста внутри Medium editor
- [ ] Реализовать переключение между Medium Editor и Markdown
- [ ] Реализовать возможность загрузки изображений в пост
- [ ] Реализовать  [Возможность указывать соотношение вознаграждения](https://github.com/GolosChain/tolstoy/issues/509)
- [ ] Внедрить [Предупреждение о точке в конце заголовка](https://github.com/GolosChain/tolstoy/issues/506)

**Comment by NickShtefan** [comment]
![2017-11-09_17-09-24](https://user-images.githubusercontent.com/6249597/32609446-d5ea8ea0-c570-11e7-8fe7-c816a7489256.gif)

Медиум внедрен

**Comment by vista7** [comment]
Привет всем! сам редактор появился на https://testnet.golos.io/ , но он работает как то коряво... Пишу пост, в конце жму на "обновить пост", страница просто обновляется и пост не добавляется никуда.

**Comment by NickShtefan** [comment]
Пока я скрещиваю Medium и  Markdown, предлагаю обсудить какие возможности форматирования должны быть доступны через Medium
И того, что очевидно
## Заголовок (h2)
###  Заголовок (h3)
**bold**
_italic_
 > Цитаты
[Ссылки](https://github.com/GolosChain/tolstoy/issues/453)

1. Списки 
2. Нумерованные

-  И 
-  списки 
- точками

Пишите, какие еще варианты форматирования нужны.

**Comment by Chiliec** [comment]
код желательно

**Comment by professor-fortran** [comment]
Было бы неплохо, если бы вы создали с десяток другой постов, чтобы пока вы прикручиваете новый редактор можно было тестировать остальной функционал (голосование, комментарии и прочее). А так получается, что тестирование, на которое отведено 2 недели, просто встало.

**Comment by professor-fortran** [comment]
Хотелось бы в редакторе иметь возможность использовать свои CSS стили. Кроме того, не знаю как в новом редакторе, но нынешний markdown редактор сильно урезан и не позволяет делать некоторые элементарные вещи, вроде жирного курсивного текста с подчеркиванием.

**Comment by NickShtefan** [comment]
> Было бы неплохо, если бы вы создали с десяток другой постов, чтобы пока вы прикручиваете новый редактор, можно было тестировать остальной функционал (голосование, комментарии и прочее). А так получается, что тестирование, на которое отведено 2 недели, просто встало.
На время тестирования редактор откатили на предыдущий.

**Comment by NickShtefan** [comment]
> Кроме того, не знаю как в новом редакторе, но нынешний markdown редактор сильно урезан и не позволяет делать некоторые элементарные вещи, вроде жирного курсивного текста с подчеркиванием.
Эти функции будут в новом редакторе. 
> Хотелось бы в редакторе иметь возможность использовать свои CSS стили. 
Дело в том, что весь контент записывается в blockchain, а у блока есть ограничение на количество информации, которую в него можно записать. Помимо внедрения различных вариантов верстки, новый редактор преследует цель избавиться от html тегов, которые занимают достаточно много места, в пользу markdown, чтобы освободить это больше места для пользовательского контента.

**Comment by NickShtefan** [comment]
@Chiliec Добавил в список выше

**Comment by jevgenika** [comment]
- [ ] сохранить htm редактор
- [ ] дать возможность пользователям протестировать новый редактор в песочнице

**Comment by NickShtefan** [comment]
В рамках данного таска так же необходимо решить ряд других тасков, чтобы можно было считать задачу закрытой. Так же важно собрать пользовательские отзывы, для уточнения необходимых функций редактора. 
#475 #509 #506 #475 #483 #435 #387 #409 #353 #476 #572 #327

**Comment by jevgenika** [comment]
- [ ] Перенести функционал выбора и загрузку изображения в верхнюю панель редактора
- [ ] Убрать диалоговое окно, запрашивать ссылку в баре редактора 
- [ ] Скрыть настройку "Национальный язык"
- [ ] удалить рамки текстового поля и линию, отделяющую от заголовка. 
- [ ] Убрать капс с "Проголосовать за пост"
- [ ] Сделать проверку на капс в заголовке, заголовок не может состоять только из капса
- [ ] Добавить всплывающие подсказки на пункты  - Награды" 50/50, "Сила голоса 100%, отказаться от выплат
- [ ]подсказки для бара редактора прописать на языке интерфейса Предпросмотр, Добавить картинку и т.д.
- [ ] реализовать функционал плавающего бара редактора

**Comment by kuchinskaya** [comment]
1) Визуально есть ощущение, что текст в кнопке не посередине, а больше заваливается в низ http://prntscr.com/jzkbkr

2) Все должно быть большими буквами (Roboto, Medium, 18px, меж буквенный интервал - 1,4) http://prntscr.com/jzke8t должно быть: http://prntscr.com/jzkkir

3) Не тот шрифт: http://prntscr.com/jzklsk должно быть:
Заголовок - Roboto Slab, Основной текст - Roboto

4) Расстояние между иконками должно быть больше: http://prntscr.com/jzkt0i как тут: http://prntscr.com/jzkuqu

5) вместо этой иконки http://prntscr.com/jzkw06 должна быть иконка info http://prntscr.com/jzkwhc

6) Эта иконка http://prntscr.com/jzkx2e должна быть всегда на круглой подложке, при наведении иконка становится синей.

7) тут меж буквенный интервал 1,4 http://prntscr.com/jzkyce

8) Я думаю что подсказка должна появляться при каждом наведении на это поле: http://prntscr.com/jzl0cg

9) нельзя давать возможность писать больше 24 знаков http://prntscr.com/jzl2l0 не удобно потом удалять

10) сообщение об ошибке должно появиться не тогда когда пользователь написал 6-й тег, а как он только навел на поле ввода http://prntscr.com/jzl3w4

11) + не тот http://prntscr.com/jzl5mq должен быть такой http://prntscr.com/jzl6uq при наведении становится синим.

12) Не тот оттенок синего у иконок: http://prntscr.com/jzl796 если нужны ресурсы, напишите мне.

13) крестик должен быть серым: http://prntscr.com/jzl8dy таким: http://prntscr.com/jzl926

**Comment by jevgenika** [comment]
1. Добавление картинки в обоих тулбарах должно работать идентично.
Решение:
- [ ] Пользователь нажимает на пункт добавления картинки в обоих тулбарах, показываем окно с 2 опциями- загрузить с компа или указать ссылку.
- [ ] заменить окно добавления картинки

2.  - [ ] добавить поле ввода имени ссылки в диалоговом окне при вводе ссылки
- [ ]  для редактирования ссылки определять ссылку и выводить диалоговое окно уже с введенной ссылкой для ее редактирования

3.  - [ ] нумерованный список должен выдавать список номеров по возрастанию

4. Кавычки не отображаются кавычками, используют отступ цитаты
- [ ] Использовать открывающие и закрывающие кавычки для выделения текста ””

5. Количество редакторов и название ничего не говорит казуальным пользователям.
Решение: 
- [ ] оставить 2 редактора (пока), 
- [ ] переименовать в Новый редактор" и "HTML редактор"

6. Сделать кнопку пост активной при заполнения всех полей: заголовок, текст, теги.

7. По активации кнопки 18+ добавлять тег nsfw

8. - [ ] Дополнить текст всплывающих подсказок про выплаты по постам
- [ ] добавить всплывающую подсказку для выбранной опции отказ от выплат
- [ ] заменить неясный текст: установки награды за свой пост  - на выбери тип награды за свой пост.
