### ISSUE TITLE
[Bug report 15.02.2018 - mobile] Проблемы верстки мобильной версии сайта

### ISSUE THREAD

**Issue by BaroH4er** [GolosChain/tolstoy#600]
# Part 1

## Страница пользователя

 - ###  **width <= 365px - `UserProfile__top-menu` уезжает**

![galaxy5-5](https://user-images.githubusercontent.com/21989598/36124905-f4663324-1062-11e8-9aa5-b6e3cc9ed3c5.png)

 - ### **width > 640px || < 750px - `UserProfile__buttons` уезжает. При том, если  width > 750px, кнопки "подписаться" или "заблокировать" часто загораживают заголовок.**   

![galaxy5-7](https://user-images.githubusercontent.com/21989598/36124908-f4a48214-1062-11e8-9f9a-6e6fa0ee6974.png)
![galaxy5-8](https://user-images.githubusercontent.com/21989598/36124910-f4ce4216-1062-11e8-939f-109358852c7a.png)

 - ### **История Scroll загораживает кнопку переключение страниц**   

![gifts](https://user-images.githubusercontent.com/21989598/36126719-ccbee124-106a-11e8-8f09-1e600f49a999.png)

 ## Страница ленты - шапка

 - ### **width 750 - 975px Кнопка меню "Новости Golos.io" - Загораживает Лого и ссылку на "Google play"**
![header-1](https://user-images.githubusercontent.com/21989598/36182100-0214c6d0-1139-11e8-8e13-0a561679b5d3.png)

 
_Страница пользователя_

- [x] **width <= 365px - `UserProfile__top-menu` уезжает**
- [x]  **width > 640px || < 750px - `UserProfile__buttons` уезжает. При том, если  width > 750px, кнопки "подписаться" или "заблокировать" часто загораживают заголовок.**   
- [x]  **История Scroll загораживает кнопку переключение страниц** 
 
_Страница ленты - шапка_

- [x] **width 750 - 975px Кнопка меню "Новости Golos.io" - Загораживает Лого и ссылку на "Google play"**

**Comment by Bacher** [comment]
"История Scroll загораживает кнопку переключение страниц" сейчас уже не актуально, так как добавился футер, и теперь всегда есть местро проскролить ниже.

**Comment by Bacher** [comment]
Блок багов "Страница ленты - шапка" тоже уже не актуальны. Блок переделан.

**Comment by BaroH4er** [comment]
@Bacher а с этими что делаем? 

- _width <= 365px - UserProfile__top-menu уезжает_
- _width > 640px || < 750px - UserProfile__buttons уезжает._

@jevgenika - решение для " _**кнопки "подписаться" или "заблокировать"**_ " кроется в редизайне  страницы пользователя. Найти решение без редизайна, конкретно к этой проблеме - проблематично, хоть и возможно. Но нужно ли?

**Comment by Bacher** [comment]
* width <= 365px - UserProfile__top-menu уезжает
* width > 640px || < 750px - UserProfile__buttons уезжает.
Вот их я как раз починил. Сейчас уточню, смержен ли мой код.

**Comment by BaroH4er** [comment]
Исправлено.
