### ISSUE TITLE
Реализация private messaging 

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#603]
Реализовать возможность использования приватного общения на платформе golos.io

Функциональные возможности

Получение списка входящих сообщений
Получения списка отправленных сообщенией
Просмотр отдельно взятого сообщения как входящего, так и исходящего
Отправка приватного сообщения
Возможность ответить на входящее сообщение
Формирование списка контактов 
Нотификации о поступивших событиях относящихся к объекту сообщений пользователя (требуется интеграция с сервисом нотификаций)

**Comment by pavelit** [comment]
Разработка виджета личных сообщений:
- [ ] Реализовать интерфейс отображения входящих и отправленных сообщений в виде всплывающего окна;
- [ ] Реализовать интерфейс для отправки сообщения;
- [ ] Реализовать возможность ответить на входящее сообщение;
- [ ] Реализовать возможность написать сообщение пользователю в местах где ссылка на аккаунт пользователя ведет на всплывающее окно информации о пользователе;
- [ ] Интегрировать систему оповещения новых сообщений;

**Comment by erikkartmen** [comment]
> Формирование списка контактов

Не вижу смысла, так как малое количество "живых" юзеров, множество твинков и боты, само собой!
